### ISSUE TITLE
Change Login option

### ISSUE THREAD

**Issue by shivank01** [p-society/Online_Rosie_FrontEnd#5]
Many students are complaining the issue of "User doesn't exist". Actually what they were trying to do is login using their id instead of email. So, what we can do is if they enter a id instead of email we can give the warning or we can change the login option to college id instead of mail.
CC- @knrt10

**Comment by knrt10** [comment]
Ok will do.

**Comment by knrt10** [comment]
Done

**Comment by AbhiRepository** [comment]
Messi!!!

**Comment by knrt10** [comment]
Ronaldo
