### ISSUE TITLE
Change Coupon design

### ISSUE THREAD

**Issue by shivank01** [p-society/Online_Rosie_FrontEnd#7]
Improve the spacing in coupons and make borders. Like the previous one
![abc](https://user-images.githubusercontent.com/22510918/44947661-586bf980-ae2e-11e8-880b-b3287db9524f.png)
@p-society/2021-batch Anyone wants to do this?

**Comment by knrt10** [comment]
Solved most of it as possible. Reopen this issue only if anyone is able to get table width 50% i.e half of page. but that is not possible. So closing this.
